### ISSUE TITLE
Cable offset increases the further you are from the center of the world (0,0,0). (Visual Glitch)

### ISSUE THREAD

**Issue by AALUND13** [Faolon12/Tethers-Powerlines#4]
The cable offset increases the further you are from the center of the world (0,0,0).
There is a screenshot 60,000km away from the center
![Screenshot 2024-08-07 214511](https://github.com/user-attachments/assets/e5d2fba5-5ebb-4c4a-a9bc-6ca0cc223aa1)

**Comment by Faolon12** [comment]
Do you want to double check and see if its fixed? ive updated the code and published,

**Comment by AALUND13** [comment]
Yup after you updated the mod it worked correctly now.
![image](https://github.com/user-attachments/assets/849b6578-4f13-4ff8-9c97-fdfa118b354a)
